# Generated by Django 4.2.10 on 2024-02-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sugar", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
    ]
